### root domain test
GET http://localhost:8000



======Admin API ===========

### get admin api
GET http://localhost:8000/api/v1/admin/



### post admin api
POST http://localhost:8000/api/v1/admin/
Content-Type: application/json

{
    "fname":"Admin",
    "lname":"admin",
    "dob":"1990-04-09",
    "email":"minal123@gmail.com",
    "password":"admin",
    "phone":"0123456789",
    "address":"sydney"
}



### post admin api
POST http://localhost:8000/api/v1/admin/verify-email
Content-Type: application/json

{
    
    "email":"minal123@gmail.com",
    "emailValidationCode":"762f5b42-0895-4263-8c0e-441987d96418"
}



### post admin api
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{
    
    "email":"minal123@gmail.com",
    "password":"1234567"
    
}